openapi: 3.0.0
info:
  title: Currency API (MVP)
  version: 1.0.0
  description: A minimal viable product (MVP) version of the Currency API.

paths:
  /currencies:
    get:
      summary: Get all currencies
      responses:
        '200':
          description: A list of all currencies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
    post:
      summary: Add a new currency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrencyInput'
      responses:
        '201':
          description: Currency successfully created

  /currencies/search:
    get:
      summary: Search currencies by filters
      parameters:
        - name: iso_code
          in: query
          schema:
            type: string
          description: ISO code (e.g. USD)
        - name: name
          in: query
          schema:
            type: string
          description: Currency name
        - name: symbol
          in: query
          schema:
            type: string
          description: Currency symbol (e.g. $)
        - name: country
          in: query
          schema:
            type: string
          description: Country name
        - name: is_active
          in: query
          schema:
            type: boolean
          description: Whether currency is active
      responses:
        '200':
          description: Matching currencies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'

  /currencies/{id}:
    put:
      summary: Update a currency by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrencyInput'
      responses:
        '200':
          description: Currency updated successfully

    delete:
      summary: Delete a currency by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Currency deleted successfully

components:
  schemas:
    Currency:
      type: object
      properties:
        id:
          type: integer
          example: 1
        iso_code:
          type: string
          example: "USD"
        name:
          type: string
          example: "US Dollar"
        symbol:
          type: string
          example: "$"
        country:
          type: string
          example: "United States"
        is_active:
          type: boolean
          example: true

    CurrencyInput:
      type: object
      required:
        - iso_code
        - name
        - symbol
        - country
        - is_active
      properties:
        iso_code:
          type: string
          example: "USD"
        name:
          type: string
          example: "US Dollar"
        symbol:
          type: string
          example: "$"
        country:
          type: string
          example: "United States"
        is_active:
          type: boolean
          example: true
